spring:
  application:
    name: "arfin"

  main:
    banner-mode: "off"

  datasource:
    url: jdbc:sqlite:arfin.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: "error"

---
spring:
  config:
    activate:
      on-profile: "server"
logging:
  level:
    root: "info"

---
spring:
  config:
    activate:
      on-profile: "dev"
logging:
  level:
    root: "debug"
